flowchart TD
    subgraph Views [Capa de Vistas]
        CLI[ConsoleMenu CLI]
    end

    subgraph Controllers [Capa de Controladores]
        CM[CreditManager]
    end

    subgraph Models [Capa de Modelos]
        Person[Person / Customer / Analyst]
        Credit[CreditApplication]
        Payment[PaymentSchedule / Installment]
    end

    subgraph Exceptions [Capa de Excepciones]
        IDE[InvalidDataException]
    end

    User((Usuario)) -->|Interacciones (Opciones 1 al 9)| CLI
    
    CLI -->|Maneja flujo y transfiere datos a| CM
    CLI -.->|Atrapa excepciones| IDE

    CM -->|Crea y Almacena| Person
    CM -->|Gestiona e Invoca evaluación delegada| Credit
    
    Credit -->|Si es aprobado, calcula y genera| Payment
    Credit -.->|Valida reglas y lanza| IDE
    Person -.->|Valida reglas y lanza| IDE
    Payment -.->|Valida matemática y lanza| IDE
