flowchart TD
    subgraph Views [Capa de Vistas]
        CLI[ConsoleMenu CLI]
    end

    subgraph Controllers [Capa de Controladores]
        CM[CreditManager]
    end

    subgraph Models [Capa de Modelos]
        Person[Person / Customer]
        Credit[CreditApplication]
        Payment[PaymentSchedule / Installment]
    end

    subgraph Exceptions [Capa de Excepciones]
        IDE[InvalidDataException]
    end

    User((Usuario)) -->|Interacciones CLI| CLI
    
    CLI -->|Maneja flujo y llama a| CM
    CLI -.->|Atrapa excepciones| IDE

    CM -->|Crea y Almacena| Person
    CM -->|Gestiona e Invoca evaluación| Credit
    
    Credit -->|Si es aprobado, genera| Payment
    Credit -.->|Valida y lanza| IDE
    Person -.->|Valida y lanza| IDE
    Payment -.->|Valida y lanza| IDE
