flowchart TD
    subgraph Views ["Capa de Vistas"]
        CLI["ConsoleMenu CLI"]
    end

    subgraph Controllers ["Capa de Controladores"]
        CM["CreditManager"]
    end

    subgraph Models ["Capa de Modelos"]
        Person["Person, Customer, Analyst"]
        Credit["CreditApplication"]
        Payment["PaymentSchedule, Installment"]
    end

    subgraph Exceptions ["Capa de Excepciones"]
        IDE["InvalidDataException"]
    end

    User((Usuario)) -->|Interacciones| CLI
    
    CLI -->|Llama a| CM
    CLI -. Atrapa excepciones .-> IDE

    CM -->|Crea y Almacena| Person
    CM -->|Gestiona| Credit
    
    Credit -->|Genera| Payment
    Credit -. Lanza .-> IDE
    Person -. Lanza .-> IDE
    Payment -. Lanza .-> IDE
